DROP TABLE IF EXISTS CASA;
DROP TABLE IF EXISTS HABITACION;
DROP TABLE IF EXISTS CONTENEDOR;
DROP TABLE IF EXISTS ELEMENTO;


CREATE TABLE CASA (
cas_id INT AUTO_INCREMENT NOT NULL UNIQUE,
cas_nombre VARCHAR(20) NOT NULL UNIQUE,
cas_desc VARCHAR(200),
PRIMARY KEY(cas_nombre)
);

CREATE TABLE HABITACION (
hab_id INT AUTO_INCREMENT NOT NULL UNIQUE,
hab_casa INT NOT NULL UNIQUE,
hab_nombre VARCHAR(20) NOT NULL,
hab_desc VARCHAR(200),
PRIMARY KEY(hab_nombre)
);

CREATE TABLE CONTENEDOR (
con_id INT AUTO_INCREMENT NOT NULL UNIQUE,
con_habitacion INT NOT NULL UNIQUE,
con_nombre VARCHAR(20) NOT NULL,
con_desc VARCHAR(200),
PRIMARY KEY(con_nombre)
);

CREATE TABLE ELEMENTO (
ele_id INT AUTO_INCREMENT NOT NULL UNIQUE,
ele_contenedor INT NOT NULL,
ele_nombre VARCHAR(20) NOT NULL UNIQUE,
ele_desc VARCHAR(200),
ele_cantidad INT NOT NULL DEFAULT 1,
ele_fechacad DATE,
PRIMARY KEY(ele_nombre)
);

ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_hab_casa_CASA_cas_id FOREIGN KEY (hab_casa) REFERENCES CASA(cas_id);
ALTER TABLE CONTENEDOR ADD CONSTRAINT CONTENEDOR_con_habitacion_HABITACION_hab_id FOREIGN KEY (con_habitacion) REFERENCES HABITACION(hab_id);
ALTER TABLE ELEMENTO ADD CONSTRAINT ELEMENTO_ele_contenedor_CONTENEDOR_con_id FOREIGN KEY (ele_contenedor) REFERENCES CONTENEDOR(con_id);